### ISSUE TITLE
学号规则未考虑到研究生

### ISSUE THREAD

**Issue by Rhilip** [RanchoTuring/GoOutApproval#1]
目前学号规则为10位数字的本科生格式，而研究生学号规则为 `三位英文字母+10位数字+1位英文字母`。
请问是否会针对以上规则进行patch或者fix？

**Comment by RanchoTuring** [comment]
同学你好，由于研究生外出审批需要涉及到【导师，学院，学生】三方，与本科生的申请审批处理逻辑不同，因此目前版本仅对本科生外出申请进行了支持。
如果后续本项目被学校采用的话，将会重构相关模块，增加对研究生外出申请的支持。
